name: CI Tests

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r RenAIssance_Transformer/requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest